# 'sudo' is enabled automatically by the 'apt' addon below.
# sudo: false 
# sudo: required

language: python            # this works for Linux but is an error on macOS or Windows

# https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems
# https://docs.travis-ci.com/user/reference/xenial#python-support
# https://scikit-build.readthedocs.io/en/latest/installation.html
matrix:
  include:
  - name: Python 2.7 on Xenial
    dist: xenial
    python: '2.7'
    compiler: gcc
    # addons:
    #   apt:
    #     sources:
    #     # - ubuntu-toolchain-r-test
    #     # - docker-xenial
    #     packages:
    #     - build-essential
    env:
    - OS_VERSION="xenial"
  - name: Python 3.5 on Xenial
    dist: xenial
    python: '3.5'
    compiler: gcc
    # addons:
    #   apt:
    #     sources:
    #     - ubuntu-toolchain-r-test
    #     packages:
    #     - build-essential
    env:
    - OS_VERSION="xenial"
  - name: Python 3.6 on Xenial
    dist: xenial
    python: '3.6'
    compiler: gcc
    # addons:
    #   apt:
    #     sources:
    #     - ubuntu-toolchain-r-test
    #     packages:
    #     - openni2-utils
    #     - build-essential
    env:
    - OS_VERSION="xenial"
  - name: Python 3.7 on Xenial
    dist: xenial
    python: '3.7'
    compiler: gcc
    # addons:
    #   apt:
    #     sources:
    #     - ubuntu-toolchain-r-test
    #     packages:
    #     - openni2-utils
    #     - build-essential
    env:
    - OS_VERSION="xenial"
  # - name: Python 2.7 on Xenial(clang)
  #   dist: xenial
  #   python: '2.7'
  #   compiler: clang
  #   addons:
  #     apt:
  #       sources:
  #       - ubuntu-toolchain-r-test
  #   env:
  #   - OS_VERSION="xenial"
  # - name: Python 3.5 on Xenial(clang)
  #   dist: xenial
  #   python: '3.5'
  #   compiler: clang
  #   addons:
  #     apt:
  #       sources:
  #       - ubuntu-toolchain-r-test
  #       packages:
  #       - openni2-utils
  #   env:
  #   - OS_VERSION="xenial"
  # - name: Python 3.6 on Xenial(clang)
  #   dist: xenial
  #   python: '3.6'
  #   compiler: clang
  #   addons:
  #     apt:
  #       sources:
  #       - ubuntu-toolchain-r-test
  #       packages:
  #       - openni2-utils
  #   env:
  #   - OS_VERSION="xenial"
  # - name: Python 3.7 on Xenial(clang)
  #   dist: xenial
  #   python: '3.7'
  #   compiler: clang
  #   addons:
  #     apt:
  #       sources:
  #       - ubuntu-toolchain-r-test
  #       packages:
  #       - openni2-utils
  #   env:
  #   - OS_VERSION="xenial"
  - name: Python 2.7.16 on macOS
    os: osx
    language: generic
    env:
    - PYTHON_VERSION=2.7.16
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
  - name: Python 3.5.7 on macOS
    os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.5.7
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
  - name: Python 3.6.8 on macOS
    os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.6.8
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
  - name: Python 3.7.3 on macOS
    os: osx
    language: generic
    env:
    - PYTHON_VERSION=3.7.3
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
cache:
  - pip
  - ccache


install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - pip install wheel
  - pip install twine
  # coveralls
  # - pip install pytest
  # - pip install coveralls
  # codecov
  # - pip install pytest-cov
  # - pip install codecov

  - if [ ${TRAVIS_OS_NAME} = "osx" ]; then
      python setup.py build_ext -i --plat-name macosx-10.9-x86_64;
      python setup.py bdist_wheel --plat-name macosx-10.9-x86_64;
    else
      python setup.py build_ext -i;
      python setup.py install;
      python setup.py bdist_wheel;
    fi

# command to run tests
script:
  # - nosetests --verbose
  # - coverage run --parallel-mode tests/pi_calculator_test.py
  # - coverage run --parallel-mode tests/rect_test.py
  # - nosetests --with-coverage --cover-erase --cover-package=scikit-build-template --verbose
  - nosetests ./tests/test_rect.py --with-coverage
  # - py.test --cov pcl
  # examples
  # - python examples/CallTest.py

after_success:
  # coveralls.io
  - coverage combine
  - coveralls
  # codecov.io
  # - codecov

deploy:
  provider: pypi
  user: sirokujira
  on:
    # test
    branch: master
    distributions: "sdist bdist_wheel"
    skip_existing: true
  password:
    secure: UXpQTei92EkJDvtIOhLdtYhhcE0jw1fiddjiKmjUvAG8U1haKO2csoEriORm4iINLvXbuz2D9fb1HL0rpNsbAjhwEN6Y0cct3UzsetISxlSr7Oq4bAcfThV3+tgt5QKvm3WGo2DyjnhXe1hiLfmbO1rS9Snd+fKnxusJyTfqvnF9qqoaUjyJMcPDm6iIMgJbfKScCjQZl6Umwgn9Z2Q061aoVstUawx8cktCrIIID6IydeaMN8KT34moYnxBE95pGVdaaeYhFJS4SboigEeM01Ws51qg/MRRhWRF1l2SlCfYzwlKFHeqZcBjhxKKtvg5jcuPHtHLkdAQrY0CfC6VU3ong3RA35yZZAelcxQrVdr9NFBler1iYjXUlSH6QZpsz/H9P6r/lTQ23nrfd+G4GEXcO8fXhZxZ3l0Kon+MM5WfGf/k1Hd1CAvwHoLQe68AeymIH+h60Oj733oCcioogxBGjnq0P6/CRvEU6Nxdca+Dcd7fpXf73jaURPHLhgK751J2z405nHN4Hf9wfD03Dw1VisLziU5FDq7oqh8eK963qKG1p5KHhtKBpcqxPF/vcyUKO0L3KX0j9GflhlXtpQRUHPG6EKi9YwCbDaYdeWUpjBVfgjxmgMAjbU6Kz2Az9ghyup3mYYxOGR04QJ1y/WQ8KKDzFruYxRgz55glx0E=
