name: cython-scikit-build-template

channels:
- defaults
dependencies:
  # - python=3.6
  # 2.1.x exhale ng?
  - Sphinx=2.0
  #- doxygen
  - Cython>=0.25.2
  - scikit-build
  - cmake
  - numpy>=1.15
  - setuptools_scm
  #- sphinx-rtd-theme
  - pip
  - pip:
  #   - scikit-build
    - cmake>=3.13
  #   - setuptools_scm
  #   # breathe extension(Automatic C++ library API documentation generator)
  #   # - breathe>=4.13.0
  #   # - exhale
  #   - sphinx-rtd-theme
    - matplotlib  
