name: cython-scikit-build-template

channels:
- !!python/unicode
  'conda-forge'
  # - anaconda

dependencies:
  - python>=3.6
  # 2.1.x exhale ng?
  - Sphinx==2.0
  - doxygen
  - scikit-build
  - cmake>=3.13
  #- sphinx-rtd-theme
  # - pip:
  #   - scikit-build
  #   - cmake>=3.13.3
  #   # breathe extension(Automatic C++ library API documentation generator)
  #   # - breathe>=4.13.0
  #   # - exhale
  #   - sphinx-rtd-theme
    